/** Core UI bundles for ru, ko, ar, pl, tr — merged in coreTranslations.js */

const authRu = { createAccount: "Создать аккаунт", welcomeBack: "С возвращением", continueGoogle: "Продолжить с Google", continueOutlook: "Продолжить с Outlook", continueKick: "Продолжить с Kick", continueTwitch: "Продолжить с Twitch", or: "или", emailAddress: "Электронная почта", identifier: "Email, gamertag или название клуба", password: "Пароль", confirmPassword: "Подтвердите пароль", passwordsDoNotMatch: "Пароли не совпадают.", signinFailed: "Не удалось войти. Попробуйте снова.", accountExists: "Аккаунт с этим email уже существует.", signupFailed: "Не удалось создать аккаунт. Попробуйте снова.", invalidSignin: "Неверный email, gamertag, клуб или пароль.", invalidEmail: "Введите корректный email.", creating: "Создание аккаунта...", signingIn: "Вход...", signIn: "Войти", signUp: "Регистрация", switchToSignin: "Уже есть аккаунт? Войти", switchToSignup: "Нет аккаунта? Регистрация", chooseLanguage: "Выберите язык", afterSignup: "После регистрации", joinDiscord: "Присоединяйтесь к Discord", discordAnytime: "Можно также присоединиться через Community в приложении" };
const authKo = { createAccount: "계정 만들기", welcomeBack: "다시 오신 것을 환영합니다", continueGoogle: "Google로 계속", continueOutlook: "Outlook으로 계속", continueKick: "Kick으로 계속", continueTwitch: "Twitch로 계속", or: "또는", emailAddress: "이메일 주소", identifier: "이메일, 게이머태그 또는 클럽 이름", password: "비밀번호", confirmPassword: "비밀번호 확인", passwordsDoNotMatch: "비밀번호가 일치하지 않습니다.", signinFailed: "로그인에 실패했습니다. 다시 시도하세요.", accountExists: "이 이메일로 이미 계정이 있습니다.", signupFailed: "계정을 만들 수 없습니다. 다시 시도하세요.", invalidSignin: "이메일, 게이머태그, 클럽 또는 비밀번호가 올바르지 않습니다.", invalidEmail: "유효한 이메일을 입력하세요.", creating: "계정 생성 중...", signingIn: "로그인 중...", signIn: "로그인", signUp: "가입", switchToSignin: "이미 계정이 있나요? 로그인", switchToSignup: "계정이 없나요? 가입", chooseLanguage: "언어 선택", afterSignup: "가입 후", joinDiscord: "Discord 커뮤니티에 참여", discordAnytime: "앱의 Community에서 언제든지 참여할 수 있습니다" };
const authAr = { createAccount: "إنشاء حساب", welcomeBack: "مرحبًا بعودتك", continueGoogle: "المتابعة مع Google", continueOutlook: "المتابعة مع Outlook", continueKick: "المتابعة مع Kick", continueTwitch: "المتابعة مع Twitch", or: "أو", emailAddress: "البريد الإلكتروني", identifier: "البريد أو الاسم أو اسم النادي", password: "كلمة المرور", confirmPassword: "تأكيد كلمة المرور", passwordsDoNotMatch: "كلمتا المرور غير متطابقتين.", signinFailed: "فشل تسجيل الدخول. حاول مرة أخرى.", accountExists: "يوجد حساب بهذا البريد بالفعل.", signupFailed: "تعذّر إنشاء الحساب. حاول مرة أخرى.", invalidSignin: "بريد أو اسم أو نادي أو كلمة مرور غير صالحة.", invalidEmail: "يرجى إدخال بريد إلكتروني صالح.", creating: "جارٍ إنشاء الحساب...", signingIn: "جارٍ تسجيل الدخول...", signIn: "تسجيل الدخول", signUp: "إنشاء حساب", switchToSignin: "لديك حساب؟ سجّل الدخول", switchToSignup: "ليس لديك حساب؟ سجّل", chooseLanguage: "اختر اللغة", afterSignup: "بعد التسجيل", joinDiscord: "انضم إلى مجتمع Discord", discordAnytime: "يمكنك الانضمام أيضًا من Community في التطبيق" };
const authPl = { createAccount: "Utwórz konto", welcomeBack: "Witaj ponownie", continueGoogle: "Kontynuuj z Google", continueOutlook: "Kontynuuj z Outlook", continueKick: "Kontynuuj z Kick", continueTwitch: "Kontynuuj z Twitch", or: "lub", emailAddress: "Adres e-mail", identifier: "E-mail, gamertag lub nazwa klubu", password: "Hasło", confirmPassword: "Potwierdź hasło", passwordsDoNotMatch: "Hasła nie są zgodne.", signinFailed: "Logowanie nie powiodło się. Spróbuj ponownie.", accountExists: "Konto z tym e-mailem już istnieje.", signupFailed: "Nie udało się utworzyć konta. Spróbuj ponownie.", invalidSignin: "Nieprawidłowy e-mail, gamertag, klub lub hasło.", invalidEmail: "Wprowadź prawidłowy adres e-mail.", creating: "Tworzenie konta...", signingIn: "Logowanie...", signIn: "Zaloguj się", signUp: "Zarejestruj się", switchToSignin: "Masz już konto? Zaloguj się", switchToSignup: "Nie masz konta? Zarejestruj się", chooseLanguage: "Wybierz język", afterSignup: "Po rejestracji", joinDiscord: "Dołącz do społeczności Discord", discordAnytime: "Możesz też dołączyć z Community w aplikacji" };
const authTr = { createAccount: "Hesap oluştur", welcomeBack: "Tekrar hoş geldin", continueGoogle: "Google ile devam et", continueOutlook: "Outlook ile devam et", continueKick: "Kick ile devam et", continueTwitch: "Twitch ile devam et", or: "veya", emailAddress: "E-posta adresi", identifier: "E-posta, gamertag veya kulüp adı", password: "Şifre", confirmPassword: "Şifreyi onayla", passwordsDoNotMatch: "Şifreler eşleşmiyor.", signinFailed: "Giriş başarısız. Tekrar dene.", accountExists: "Bu e-posta ile zaten bir hesap var.", signupFailed: "Hesap oluşturulamadı. Tekrar dene.", invalidSignin: "Geçersiz e-posta, gamertag, kulüp veya şifre.", invalidEmail: "Lütfen geçerli bir e-posta gir.", creating: "Hesap oluşturuluyor...", signingIn: "Giriş yapılıyor...", signIn: "Giriş Yap", signUp: "Kayıt Ol", switchToSignin: "Zaten hesabın var mı? Giriş Yap", switchToSignup: "Hesabın yok mu? Kayıt Ol", chooseLanguage: "Dil seç", afterSignup: "Kayıt sonrası", joinDiscord: "Discord topluluğumuza katıl", discordAnytime: "Uygulamadaki Community üzerinden de katılabilirsin" };

const settingsRu = { title: "Настройки", subtitle: "Язык, звуки, тема и аккаунт", languageTitle: "Язык", languageDescription: "Выберите предпочитаемый язык", saveChanges: "Сохранить", saving: "Сохранение...", saved: "Настройки сохранены" };
const settingsKo = { title: "설정", subtitle: "언어, 소리, 테마 및 계정", languageTitle: "언어", languageDescription: "선호하는 언어를 선택하세요", saveChanges: "변경 사항 저장", saving: "저장 중...", saved: "설정이 저장되었습니다" };
const settingsAr = { title: "الإعدادات", subtitle: "اللغة والأصوات والمظهر والحساب", languageTitle: "اللغة", languageDescription: "اختر لغتك المفضلة", saveChanges: "حفظ التغييرات", saving: "جارٍ الحفظ...", saved: "تم حفظ الإعدادات" };
const settingsPl = { title: "Ustawienia", subtitle: "Język, dźwięki, motyw i konto", languageTitle: "Język", languageDescription: "Wybierz preferowany język", saveChanges: "Zapisz zmiany", saving: "Zapisywanie...", saved: "Ustawienia zapisane" };
const settingsTr = { title: "Ayarlar", subtitle: "Dil, sesler, tema ve hesap", languageTitle: "Dil", languageDescription: "Tercih ettiğin dili seç", saveChanges: "Değişiklikleri kaydet", saving: "Kaydediliyor...", saved: "Ayarlar kaydedildi" };

const mobileRu = { guide: "Гид", openGuide: "Открыть гид {label}", closeGuide: "Закрыть гид", previousStep: "Предыдущий шаг", nextStep: "Следующий шаг", stepCount: "Шаг {current} из {total}", next: "Далее", done: "Готово" };
const mobileKo = { guide: "가이드", openGuide: "{label} 가이드 열기", closeGuide: "가이드 닫기", previousStep: "이전 단계", nextStep: "다음 단계", stepCount: "단계 {current}/{total}", next: "다음", done: "완료" };
const mobileAr = { guide: "دليل", openGuide: "فتح دليل {label}", closeGuide: "إغلاق الدليل", previousStep: "الخطوة السابقة", nextStep: "الخطوة التالية", stepCount: "الخطوة {current} من {total}", next: "التالي", done: "تم" };
const mobilePl = { guide: "Przewodnik", openGuide: "Otwórz przewodnik {label}", closeGuide: "Zamknij przewodnik", previousStep: "Poprzedni krok", nextStep: "Następny krok", stepCount: "Krok {current} z {total}", next: "Dalej", done: "Gotowe" };
const mobileTr = { guide: "Rehber", openGuide: "{label} rehberini aç", closeGuide: "Rehberi kapat", previousStep: "Önceki adım", nextStep: "Sonraki adım", stepCount: "Adım {current}/{total}", next: "İleri", done: "Bitti" };

const navRu = { home: "Главная", welcome: "Добро пожаловать", dashboard: "Панель", matches: "Матчи", compete: "Соревнования", club: "Клуб", more: "Ещё", schedule: "Расписание", inbox: "Inbox", notifications: "Уведомления", tournaments: "Турниры", international: "Международные", register: "Регистрация", rankings: "Рейтинги", players: "Игроки", freeAgents: "Свободные агенты", recruitment: "Recruitment", transfers: "Трансферы", wallet: "Кошелёк", feed: "Лента", discord: "Discord", followBack: "Follow Back", profile: "Профиль", search: "Поиск", lifestyle: "Lifestyle", store: "Магазин", news: "Новости", settings: "Настройки", tournament: "Турнир", gameDay: "Match Day", trophy: "Трофей", myProfile: "Мой профиль", myClub: "Мой клуб" };
const navKo = { home: "홈", welcome: "환영합니다", dashboard: "대시보드", matches: "경기", compete: "참가", club: "클럽", more: "더보기", schedule: "일정", inbox: "받은편지함", notifications: "알림", tournaments: "토너먼트", international: "국제", register: "등록", rankings: "랭킹", players: "선수", freeAgents: "자유 에이전트", recruitment: "리크루트", transfers: "이적", wallet: "지갑", feed: "피드", discord: "Discord", followBack: "맞팔로우", profile: "프로필", search: "검색", lifestyle: "라이프스타일", store: "스토어", news: "뉴스", settings: "설정", tournament: "토너먼트", gameDay: "경기일", trophy: "트로피", myProfile: "내 프로필", myClub: "내 클럽" };
const navAr = { home: "الرئيسية", welcome: "مرحبًا", dashboard: "لوحة التحكم", matches: "المباريات", compete: "المنافسة", club: "النادي", more: "المزيد", schedule: "الجدول", inbox: "صندوق الوارد", notifications: "الإشعارات", tournaments: "البطولات", international: "دولي", register: "التسجيل", rankings: "التصنيفات", players: "اللاعبون", freeAgents: "لاعبون أحرار", recruitment: "التوظيف", transfers: "الانتقالات", wallet: "المحفظة", feed: "الخلاصة", discord: "Discord", followBack: "رد المتابعة", profile: "الملف", search: "بحث", lifestyle: "أسلوب الحياة", store: "المتجر", news: "الأخبار", settings: "الإعدادات", tournament: "بطولة", gameDay: "يوم المباراة", trophy: "الكأس", myProfile: "ملفي", myClub: "ناديي" };
const navPl = { home: "Strona główna", welcome: "Witaj", dashboard: "Panel", matches: "Mecze", compete: "Rywalizacja", club: "Klub", more: "Więcej", schedule: "Terminarz", inbox: "Skrzynka", notifications: "Powiadomienia", tournaments: "Turnieje", international: "Międzynarodowe", register: "Rejestracja", rankings: "Rankingi", players: "Gracze", freeAgents: "Wolni agenci", recruitment: "Rekrutacja", transfers: "Transfery", wallet: "Portfel", feed: "Feed", discord: "Discord", followBack: "Follow Back", profile: "Profil", search: "Szukaj", lifestyle: "Lifestyle", store: "Sklep", news: "Aktualności", settings: "Ustawienia", tournament: "Turniej", gameDay: "Match Day", trophy: "Puchar", myProfile: "Mój profil", myClub: "Mój klub" };
const navTr = { home: "Ana Sayfa", welcome: "Hoş geldin", dashboard: "Panel", matches: "Maçlar", compete: "Yarış", club: "Kulüp", more: "Daha fazla", schedule: "Program", inbox: "Gelen kutusu", notifications: "Bildirimler", tournaments: "Turnuvalar", international: "Uluslararası", register: "Kayıt", rankings: "Sıralamalar", players: "Oyuncular", freeAgents: "Serbest oyuncular", recruitment: "Kadro", transfers: "Transferler", wallet: "Cüzdan", feed: "Akış", discord: "Discord", followBack: "Takip et", profile: "Profil", search: "Ara", lifestyle: "Yaşam tarzı", store: "Mağaza", news: "Haberler", settings: "Ayarlar", tournament: "Turnuva", gameDay: "Maç Günü", trophy: "Kupa", myProfile: "Profilim", myClub: "Kulübüm" };

export const EXTENDED_LANGUAGE_NAMES = {
  ru: { en: "Russian", fr: "Russe", nl: "Russisch", es: "Ruso", pt: "Russo", it: "Russo", de: "Russisch", zh: "俄语", ja: "ロシア語", ru: "Русский", ko: "러시아어", ar: "الروسية", pl: "Rosyjski", tr: "Rusça" },
  ko: { en: "Korean", fr: "Coréen", nl: "Koreaans", es: "Coreano", pt: "Coreano", it: "Coreano", de: "Koreanisch", zh: "韩语", ja: "韓国語", ru: "Корейский", ko: "한국어", ar: "الكورية", pl: "Koreański", tr: "Korece" },
  ar: { en: "Arabic", fr: "Arabe", nl: "Arabisch", es: "Árabe", pt: "Árabe", it: "Arabo", de: "Arabisch", zh: "阿拉伯语", ja: "アラビア語", ru: "Арабский", ko: "아랍어", ar: "العربية", pl: "Arabski", tr: "Arapça" },
  pl: { en: "Polish", fr: "Polonais", nl: "Pools", es: "Polaco", pt: "Polonês", it: "Polacco", de: "Polnisch", zh: "波兰语", ja: "ポーランド語", ru: "Польский", ko: "폴란드어", ar: "البولندية", pl: "Polski", tr: "Lehçe" },
  tr: { en: "Turkish", fr: "Turc", nl: "Turks", es: "Turco", pt: "Turco", it: "Turco", de: "Türkisch", zh: "土耳其语", ja: "トルコ語", ru: "Турецкий", ko: "터키어", ar: "التركية", pl: "Turecki", tr: "Türkçe" },
};

export const EXTENDED_EXTRA_NAV = {
  ru: { community: "Сообщество", market: "Рынок", discover: "Обзор", competitions: "Соревнования", clubs: "Клубы", squad: "Состав", dashboard: "Панель", welcome: "Добро пожаловать" },
  ko: { community: "커뮤니티", market: "마켓", discover: "탐색", competitions: "대회", clubs: "클럽", squad: "스쿼드", dashboard: "대시보드", welcome: "환영합니다" },
  ar: { community: "المجتمع", market: "السوق", discover: "استكشاف", competitions: "المنافسات", clubs: "الأندية", squad: "التشكيلة", dashboard: "لوحة التحكم", welcome: "مرحبًا" },
  pl: { community: "Społeczność", market: "Rynek", discover: "Odkrywaj", competitions: "Rozgrywki", clubs: "Kluby", squad: "Skład", dashboard: "Panel", welcome: "Witaj" },
  tr: { community: "Topluluk", market: "Pazar", discover: "Keşfet", competitions: "Müsabakalar", clubs: "Kulüpler", squad: "Kadro", dashboard: "Panel", welcome: "Hoş geldin" },
};

export function buildExtendedMatchFlow(en) {
  return {
    ru: { ...en, gameDayTitle: "Match Day", scheduleTitle: "Расписание", inboxTitle: "Inbox", league: "Лига", allLeagues: "Все лиги", all: "Все", matchDetails: "Детали матча", rankedMatch: "Ранговый матч", tournament: "Турнир", scheduled: "Запланирован", live: "Live", pending: "Ожидание", fullTime: "Конец матча", tbd: "TBD", yourClub: "Ваш клуб", scheduleSubtitleAll: "Все матчи, турниры и напоминания о контрактах", fixtures: "Матчи", calendar: "Календарь", arrangeGame: "Назначить матч", home: "Дома", away: "В гостях", unknown: "Неизвестно", markAllRead: "Отметить всё прочитанным", inboxEmpty: "Inbox пуст", noMessages: "Нет сообщений", selectMessage: "Выберите сообщение", needsAction: "Требуется действие", accept: "Принять", decline: "Отклонить", cancel: "Отмена", kickoff: "Начало", chat: "Чат", stats: "Статистика" },
    ko: { ...en, gameDayTitle: "경기일", scheduleTitle: "일정", inboxTitle: "받은편지함", league: "리그", allLeagues: "모든 리그", all: "전체", matchDetails: "경기 상세", rankedMatch: "랭크전", tournament: "토너먼트", scheduled: "예정", live: "라이브", pending: "대기", fullTime: "경기 종료", tbd: "미정", yourClub: "내 클럽", scheduleSubtitleAll: "모든 경기, 토너먼트 및 계약 알림", fixtures: "경기", calendar: "캘린더", arrangeGame: "경기 조율", home: "홈", away: "원정", unknown: "알 수 없음", markAllRead: "모두 읽음", inboxEmpty: "받은편지함이 비어 있습니다", noMessages: "메시지 없음", selectMessage: "읽을 메시지 선택", needsAction: "조치 필요", accept: "수락", decline: "거절", cancel: "취소", kickoff: "킥오프", chat: "채팅", stats: "통계" },
    ar: { ...en, gameDayTitle: "يوم المباراة", scheduleTitle: "الجدول", inboxTitle: "صندوق الوارد", league: "الدوري", allLeagues: "كل الدوريات", all: "الكل", matchDetails: "تفاصيل المباراة", rankedMatch: "مباراة مصنّفة", tournament: "بطولة", scheduled: "مجدولة", live: "مباشر", pending: "قيد الانتظار", fullTime: "نهاية المباراة", tbd: "يُحدّد لاحقًا", yourClub: "ناديك", scheduleSubtitleAll: "كل المباريات والبطولات وتذكيرات العقود", fixtures: "المباريات", calendar: "التقويم", arrangeGame: "ترتيب مباراة", home: "على أرضك", away: "خارج الأرض", unknown: "غير معروف", markAllRead: "تعليم الكل كمقروء", inboxEmpty: "صندوق الوارد فارغ", noMessages: "لا رسائل", selectMessage: "اختر رسالة للقراءة", needsAction: "يتطلب إجراء", accept: "قبول", decline: "رفض", cancel: "إلغاء", kickoff: "انطلاق", chat: "دردشة", stats: "إحصائيات" },
    pl: { ...en, gameDayTitle: "Match Day", scheduleTitle: "Terminarz", inboxTitle: "Skrzynka", league: "Liga", allLeagues: "Wszystkie ligi", all: "Wszystko", matchDetails: "Szczegóły meczu", rankedMatch: "Mecz rankingowy", tournament: "Turniej", scheduled: "Zaplanowany", live: "Na żywo", pending: "Oczekujący", fullTime: "Koniec meczu", tbd: "Do ustalenia", yourClub: "Twój klub", scheduleSubtitleAll: "Wszystkie mecze, turnieje i przypomnienia o kontraktach", fixtures: "Mecze", calendar: "Kalendarz", arrangeGame: "Ustal mecz", home: "Dom", away: "Wyjazd", unknown: "Nieznany", markAllRead: "Oznacz wszystkie jako przeczytane", inboxEmpty: "Skrzynka jest pusta", noMessages: "Brak wiadomości", selectMessage: "Wybierz wiadomość", needsAction: "Wymaga działania", accept: "Akceptuj", decline: "Odrzuć", cancel: "Anuluj", kickoff: "Rozpoczęcie", chat: "Czat", stats: "Statystyki" },
    tr: { ...en, gameDayTitle: "Maç Günü", scheduleTitle: "Program", inboxTitle: "Gelen kutusu", league: "Lig", allLeagues: "Tüm ligler", all: "Tümü", matchDetails: "Maç detayları", rankedMatch: "Dereceli maç", tournament: "Turnuva", scheduled: "Planlandı", live: "Canlı", pending: "Beklemede", fullTime: "Maç bitti", tbd: "Belirlenecek", yourClub: "Kulübün", scheduleSubtitleAll: "Tüm maçlar, turnuvalar ve sözleşme hatırlatmaları", fixtures: "Maçlar", calendar: "Takvim", arrangeGame: "Maç ayarla", home: "Ev", away: "Deplasman", unknown: "Bilinmiyor", markAllRead: "Tümünü okundu işaretle", inboxEmpty: "Gelen kutusu boş", noMessages: "Mesaj yok", selectMessage: "Okumak için mesaj seç", needsAction: "İşlem gerekli", accept: "Kabul et", decline: "Reddet", cancel: "İptal", kickoff: "Başlangıç", chat: "Sohbet", stats: "İstatistikler" },
  };
}

export function buildExtendedCompetitionFlow(en) {
  return {
    ru: { ...en, competitionsTitle: "Соревнования", tournamentsTitle: "Турниры", rankingsTitle: "Рейтинги", playersTitle: "Игроки", registrationTitle: "Регистрация сезона", open: "Открыто", live: "Live", done: "Завершено", full: "Полно", rules: "Правила", createTournament: "Создать турнир", community: "Сообщество", players: "Игроки", clubs: "Клубы", entry: "Вход", prize: "Приз", free: "Бесплатно", back: "Назад", next: "Далее", global: "Глобальный", regional: "Региональный", country: "Страна", allRegions: "Все регионы", allCountries: "Все страны", searchPlayers: "Поиск игроков...", noPlayersFound: "Игроки не найдены.", applyNow: "Подать заявку", cancel: "Отмена" },
    ko: { ...en, competitionsTitle: "대회", tournamentsTitle: "토너먼트", rankingsTitle: "랭킹", playersTitle: "선수", registrationTitle: "시즌 등록", open: "모집 중", live: "라이브", done: "완료", full: "마감", rules: "규칙", createTournament: "토너먼트 만들기", community: "커뮤니티", players: "선수", clubs: "클럽", entry: "참가", prize: "상금", free: "무료", back: "뒤로", next: "다음", global: "글로벌", regional: "지역", country: "국가", allRegions: "모든 지역", allCountries: "모든 국가", searchPlayers: "선수 검색...", noPlayersFound: "선수를 찾을 수 없습니다.", applyNow: "신청", cancel: "취소" },
    ar: { ...en, competitionsTitle: "المنافسات", tournamentsTitle: "البطولات", rankingsTitle: "التصنيفات", playersTitle: "اللاعبون", registrationTitle: "تسجيل الموسم", open: "مفتوح", live: "مباشر", done: "منتهٍ", full: "مكتمل", rules: "القواعد", createTournament: "إنشاء بطولة", community: "المجتمع", players: "اللاعبون", clubs: "الأندية", entry: "الدخول", prize: "الجائزة", free: "مجاني", back: "رجوع", next: "التالي", global: "عالمي", regional: "إقليمي", country: "البلد", allRegions: "كل المناطق", allCountries: "كل البلدان", searchPlayers: "ابحث عن لاعبين...", noPlayersFound: "لم يُعثر على لاعبين.", applyNow: "قدّم الآن", cancel: "إلغاء" },
    pl: { ...en, competitionsTitle: "Rozgrywki", tournamentsTitle: "Turnieje", rankingsTitle: "Rankingi", playersTitle: "Gracze", registrationTitle: "Rejestracja sezonu", open: "Otwarte", live: "Na żywo", done: "Zakończone", full: "Pełne", rules: "Zasady", createTournament: "Utwórz turniej", community: "Społeczność", players: "Gracze", clubs: "Kluby", entry: "Wejście", prize: "Nagroda", free: "Darmowe", back: "Wstecz", next: "Dalej", global: "Globalny", regional: "Regionalny", country: "Kraj", allRegions: "Wszystkie regiony", allCountries: "Wszystkie kraje", searchPlayers: "Szukaj graczy...", noPlayersFound: "Nie znaleziono graczy.", applyNow: "Aplikuj", cancel: "Anuluj" },
    tr: { ...en, competitionsTitle: "Müsabakalar", tournamentsTitle: "Turnuvalar", rankingsTitle: "Sıralamalar", playersTitle: "Oyuncular", registrationTitle: "Sezon kaydı", open: "Açık", live: "Canlı", done: "Bitti", full: "Dolu", rules: "Kurallar", createTournament: "Turnuva oluştur", community: "Topluluk", players: "Oyuncular", clubs: "Kulüpler", entry: "Giriş", prize: "Ödül", free: "Ücretsiz", back: "Geri", next: "İleri", global: "Küresel", regional: "Bölgesel", country: "Ülke", allRegions: "Tüm bölgeler", allCountries: "Tüm ülkeler", searchPlayers: "Oyuncu ara...", noPlayersFound: "Oyuncu bulunamadı.", applyNow: "Başvur", cancel: "İptal" },
  };
}

export function buildExtendedTournamentDetail(en) {
  return {
    ru: { ...en, backToTournaments: "Назад к турнирам", tournamentNotFound: "Турнир не найден.", registerMyClub: "Зарегистрировать клуб", registerAsPlayer: "Зарегистрироваться как игрок", withdraw: "Отказаться", generateDraw: "Сгенерировать жеребьёвку", startTournament: "Начать турнир", champion: "Чемпион", tabBracket: "Сетка / Матчи", tabGroupStandings: "Групповая таблица", tabLeagueTable: "Таблица лиги", tabStats: "Статистика", tabPlayers: "Игроки", tabTeams: "Команды" },
    ko: { ...en, backToTournaments: "토너먼트로 돌아가기", tournamentNotFound: "토너먼트를 찾을 수 없습니다.", registerMyClub: "클럽 등록", registerAsPlayer: "선수로 등록", withdraw: "철회", generateDraw: "대진 생성", startTournament: "토너먼트 시작", champion: "우승", tabBracket: "대진 / 경기", tabGroupStandings: "조별 순위", tabLeagueTable: "리그 순위", tabStats: "통계", tabPlayers: "선수", tabTeams: "팀" },
    ar: { ...en, backToTournaments: "العودة إلى البطولات", tournamentNotFound: "لم تُعثر على البطولة.", registerMyClub: "سجّل ناديي", registerAsPlayer: "سجّل كلاعب", withdraw: "انسحاب", generateDraw: "إنشاء القرعة", startTournament: "بدء البطولة", champion: "البطل", tabBracket: "الجدول / المباريات", tabGroupStandings: "ترتيب المجموعات", tabLeagueTable: "جدول الدوري", tabStats: "الإحصائيات", tabPlayers: "اللاعبون", tabTeams: "الفرق" },
    pl: { ...en, backToTournaments: "Powrót do turniejów", tournamentNotFound: "Nie znaleziono turnieju.", registerMyClub: "Zarejestruj mój klub", registerAsPlayer: "Zarejestruj się jako gracz", withdraw: "Wycofaj się", generateDraw: "Generuj losowanie", startTournament: "Rozpocznij turniej", champion: "Mistrz", tabBracket: "Drabinka / Mecze", tabGroupStandings: "Tabela grup", tabLeagueTable: "Tabela ligowa", tabStats: "Statystyki", tabPlayers: "Gracze", tabTeams: "Drużyny" },
    tr: { ...en, backToTournaments: "Turnuvalara dön", tournamentNotFound: "Turnuva bulunamadı.", registerMyClub: "Kulübümü kaydet", registerAsPlayer: "Oyuncu olarak kaydol", withdraw: "Çekil", generateDraw: "Kura oluştur", startTournament: "Turnuvayı başlat", champion: "Şampiyon", tabBracket: "Eşleşme / Maçlar", tabGroupStandings: "Grup puan durumu", tabLeagueTable: "Lig tablosu", tabStats: "İstatistikler", tabPlayers: "Oyuncular", tabTeams: "Takımlar" },
  };
}

const homeNotifBundle = {
  ru: { cancel: "Отмена", loading: "Загрузка...", getStarted: "Начать", complete: "Завершить", learnMore: "Подробнее", notifTitle: "Уведомления", notifMarkAllRead: "Отметить всё прочитанным", notifDeleteAll: "Удалить всё", notifDeleteAllConfirmTitle: "Удалить все уведомления?", notifDeleteAllConfirmDesc: "Будут удалены все {count} уведомлений без возможности восстановления.", notifEmpty: "Уведомлений пока нет", notifMarkAsRead: "Отметить прочитанным", homeCompetitions: "Соревнования", homeTournaments: "Турниры", homeLeagues: "Лиги", homeTier: "Уровень {tier}", homeViewBracket: "Смотреть сетку", homePlayers: "{count}/{max} игроков", homeFull: "Полно", homeViewDetails: "Подробнее", homeNoTournaments: "Турниров пока нет.", homeNoLeagues: "Лиг пока нет.", homePlatform: "Платформа", homeViewAll: "Смотреть всё", homeLatest: "Последние", homeAllNews: "Все новости", homeUpcoming: "Скоро", homeSchedule: "Расписание", homeScheduleDesc: "Следите за каждым матчем. Match Day — центр всего.", homeGameDay: "Match Day", homeNoMatches: "Нет запланированных матчей.", homeMessages: "Сообщения", homeOpen: "Открыть", homeSignInMessages: "Войдите, чтобы видеть сообщения.", homeInboxEmpty: "Inbox пуст.", homeStageSystem: "Система STAGE", homeUnknown: "Неизвестно", homeJumpIn: "Начать", homeJumpInDesc: "Всё необходимое — в одно касание.", homeNavCompetitions: "Соревнования", homeNavCompetitionsDesc: "Лиги и кубки на выбывание", homeNavGameDay: "Match Day", homeNavGameDayDesc: "Планируй и играй матчи", homeNavClubs: "Клубы", homeNavClubsDesc: "Просматривай и управляй клубами", homeNavStore: "Магазин", homeNavStoreDesc: "Трать STC", homeFooterRankings: "Рейтинги", homeQuestions: "Вопросы", homeFaq: "FAQ", homeFaqDesc: "Частые вопросы о платформе.", homeContact: "Контакты", homeRights: "Все права защищены." },
  ko: { cancel: "취소", loading: "로딩 중...", getStarted: "시작하기", complete: "완료", learnMore: "자세히", notifTitle: "알림", notifMarkAllRead: "모두 읽음", notifDeleteAll: "모두 삭제", notifDeleteAllConfirmTitle: "모든 알림을 삭제할까요?", notifDeleteAllConfirmDesc: "{count}개의 알림이 영구 삭제됩니다. 되돌릴 수 없습니다.", notifEmpty: "알림이 없습니다", notifMarkAsRead: "읽음으로 표시", homeCompetitions: "대회", homeTournaments: "토너먼트", homeLeagues: "리그", homeTier: "티어 {tier}", homeViewBracket: "대진 보기", homePlayers: "{count}/{max} 선수", homeFull: "마감", homeViewDetails: "자세히 보기", homeNoTournaments: "토너먼트가 아직 없습니다.", homeNoLeagues: "리그가 아직 없습니다.", homePlatform: "플랫폼", homeViewAll: "전체 보기", homeLatest: "최신", homeAllNews: "모든 뉴스", homeUpcoming: "예정", homeSchedule: "일정", homeScheduleDesc: "모든 대회의 경기를 추적하세요. 경기일이 모든 것의 중심입니다.", homeGameDay: "경기일", homeNoMatches: "예정된 경기가 없습니다.", homeMessages: "메시지", homeOpen: "열기", homeSignInMessages: "메시지를 보려면 로그인하세요.", homeInboxEmpty: "받은편지함이 비어 있습니다.", homeStageSystem: "STAGE 시스템", homeUnknown: "알 수 없음", homeJumpIn: "시작", homeJumpInDesc: "필요한 모든 것을 한 번에.", homeNavCompetitions: "대회", homeNavCompetitionsDesc: "리그 및 토너먼트", homeNavGameDay: "경기일", homeNavGameDayDesc: "경기 일정 및 플레이", homeNavClubs: "클럽", homeNavClubsDesc: "클럽 탐색 및 관리", homeNavStore: "스토어", homeNavStoreDesc: "STC 사용", homeFooterRankings: "랭킹", homeQuestions: "질문", homeFaq: "FAQ", homeFaqDesc: "플랫폼에 대한 자주 묻는 질문.", homeContact: "문의", homeRights: "All rights reserved." },
  ar: { cancel: "إلغاء", loading: "جارٍ التحميل...", getStarted: "ابدأ", complete: "إكمال", learnMore: "اعرف المزيد", notifTitle: "الإشعارات", notifMarkAllRead: "تعليم الكل كمقروء", notifDeleteAll: "حذف الكل", notifDeleteAllConfirmTitle: "حذف جميع الإشعارات؟", notifDeleteAllConfirmDesc: "سيتم حذف جميع {count} إشعار/إشعارات نهائيًا.", notifEmpty: "لا إشعارات بعد", notifMarkAsRead: "تعليم كمقروء", homeCompetitions: "المنافسات", homeTournaments: "البطولات", homeLeagues: "الدوريات", homeTier: "المستوى {tier}", homeViewBracket: "عرض الجدول", homePlayers: "{count}/{max} لاعب", homeFull: "مكتمل", homeViewDetails: "عرض التفاصيل", homeNoTournaments: "لا بطولات بعد.", homeNoLeagues: "لا دوريات بعد.", homePlatform: "المنصة", homeViewAll: "عرض الكل", homeLatest: "الأحدث", homeAllNews: "كل الأخبار", homeUpcoming: "قريبًا", homeSchedule: "الجدول", homeScheduleDesc: "تابع كل مباراة في جميع المنافسات. يوم المباراة هو حيث يحدث كل شيء.", homeGameDay: "يوم المباراة", homeNoMatches: "لا مباريات مجدولة.", homeMessages: "الرسائل", homeOpen: "فتح", homeSignInMessages: "سجّل الدخول لعرض رسائلك.", homeInboxEmpty: "صندوق الوارد فارغ.", homeStageSystem: "نظام STAGE", homeUnknown: "غير معروف", homeJumpIn: "ابدأ", homeJumpInDesc: "كل ما تحتاجه بنقرة واحدة.", homeNavCompetitions: "المنافسات", homeNavCompetitionsDesc: "الدوريات وكؤوس الإقصاء", homeNavGameDay: "يوم المباراة", homeNavGameDayDesc: "جدولة ولعب المباريات", homeNavClubs: "الأندية", homeNavClubsDesc: "تصفّح وأدر الأندية", homeNavStore: "المتجر", homeNavStoreDesc: "أنفق STC", homeFooterRankings: "التصنيفات", homeQuestions: "أسئلة", homeFaq: "الأسئلة الشائعة", homeFaqDesc: "أسئلة شائعة حول المنصة.", homeContact: "اتصل", homeRights: "جميع الحقوق محفوظة." },
  pl: { cancel: "Anuluj", loading: "Ładowanie...", getStarted: "Zacznij", complete: "Ukończ", learnMore: "Dowiedz się więcej", notifTitle: "Powiadomienia", notifMarkAllRead: "Oznacz wszystkie jako przeczytane", notifDeleteAll: "Usuń wszystkie", notifDeleteAllConfirmTitle: "Usunąć wszystkie powiadomienia?", notifDeleteAllConfirmDesc: "Spowoduje to trwałe usunięcie wszystkich {count} powiadomień.", notifEmpty: "Brak powiadomień", notifMarkAsRead: "Oznacz jako przeczytane", homeCompetitions: "Rozgrywki", homeTournaments: "Turnieje", homeLeagues: "Ligi", homeTier: "Poziom {tier}", homeViewBracket: "Zobacz drabinkę", homePlayers: "{count}/{max} graczy", homeFull: "Pełne", homeViewDetails: "Zobacz szczegóły", homeNoTournaments: "Brak turniejów.", homeNoLeagues: "Brak lig.", homePlatform: "Platforma", homeViewAll: "Zobacz wszystko", homeLatest: "Najnowsze", homeAllNews: "Wszystkie wiadomości", homeUpcoming: "Nadchodzące", homeSchedule: "Terminarz", homeScheduleDesc: "Śledź każdy mecz we wszystkich rozgrywkach. Match Day to centrum akcji.", homeGameDay: "Match Day", homeNoMatches: "Brak zaplanowanych meczów.", homeMessages: "Wiadomości", homeOpen: "Otwórz", homeSignInMessages: "Zaloguj się, aby zobaczyć wiadomości.", homeInboxEmpty: "Skrzynka jest pusta.", homeStageSystem: "System STAGE", homeUnknown: "Nieznany", homeJumpIn: "Zacznij", homeJumpInDesc: "Wszystko, czego potrzebujesz, jednym kliknięciem.", homeNavCompetitions: "Rozgrywki", homeNavCompetitionsDesc: "Ligi i puchary pucharowe", homeNavGameDay: "Match Day", homeNavGameDayDesc: "Planuj i graj mecze", homeNavClubs: "Kluby", homeNavClubsDesc: "Przeglądaj i zarządzaj klubami", homeNavStore: "Sklep", homeNavStoreDesc: "Wydaj STC", homeFooterRankings: "Rankingi", homeQuestions: "Pytania", homeFaq: "FAQ", homeFaqDesc: "Często zadawane pytania o platformę.", homeContact: "Kontakt", homeRights: "Wszelkie prawa zastrzeżone." },
  tr: { cancel: "İptal", loading: "Yükleniyor...", getStarted: "Başla", complete: "Tamamla", learnMore: "Daha fazla", notifTitle: "Bildirimler", notifMarkAllRead: "Tümünü okundu işaretle", notifDeleteAll: "Tümünü sil", notifDeleteAllConfirmTitle: "Tüm bildirimler silinsin mi?", notifDeleteAllConfirmDesc: "Tüm {count} bildirim kalıcı olarak silinecek.", notifEmpty: "Henüz bildirim yok", notifMarkAsRead: "Okundu işaretle", homeCompetitions: "Müsabakalar", homeTournaments: "Turnuvalar", homeLeagues: "Ligler", homeTier: "Seviye {tier}", homeViewBracket: "Eşleşmeyi gör", homePlayers: "{count}/{max} oyuncu", homeFull: "Dolu", homeViewDetails: "Detayları gör", homeNoTournaments: "Henüz turnuva yok.", homeNoLeagues: "Henüz lig yok.", homePlatform: "Platform", homeViewAll: "Tümünü gör", homeLatest: "Son", homeAllNews: "Tüm haberler", homeUpcoming: "Yaklaşan", homeSchedule: "Program", homeScheduleDesc: "Tüm müsabakalardaki her maçı takip et. Maç Günü her şeyin merkezidir.", homeGameDay: "Maç Günü", homeNoMatches: "Planlanmış maç yok.", homeMessages: "Mesajlar", homeOpen: "Aç", homeSignInMessages: "Mesajlarını görmek için giriş yap.", homeInboxEmpty: "Gelen kutun boş.", homeStageSystem: "STAGE Sistemi", homeUnknown: "Bilinmiyor", homeJumpIn: "Başla", homeJumpInDesc: "İhtiyacın olan her şey bir dokunuş uzağında.", homeNavCompetitions: "Müsabakalar", homeNavCompetitionsDesc: "Ligler ve eleme kupaları", homeNavGameDay: "Maç Günü", homeNavGameDayDesc: "Maçları planla ve oyna", homeNavClubs: "Kulüpler", homeNavClubsDesc: "Kulüpleri keşfet ve yönet", homeNavStore: "Mağaza", homeNavStoreDesc: "STC harca", homeFooterRankings: "Sıralamalar", homeQuestions: "Sorular", homeFaq: "SSS", homeFaqDesc: "Platform hakkında sık sorulan sorular.", homeContact: "İletişim", homeRights: "Tüm hakları saklıdır." },
};

export function buildExtendedCommonPages(en) {
  const base = (lang, overrides) => ({ ...en, ...overrides });
  return {
    ru: base(en, { searchTitle: "Поиск", searchSubtitle: "Найти игроков и клубы", searchCta: "Поиск", playersTab: "Игроки", myClubsTab: "Мои клубы", invite: "Пригласить", challenge: "Вызов", view: "Смотреть", internationalTitle: "Международные", internationalLoading: "Загрузка международных турниров...", vote: "Голосовать", submitting: "Отправка...", nationalSquad: "Сборная", position: "Позиция", saveSquad: "Сохранить состав", freeAgentTitle: "Свободные агенты", freeAgentSubtitle: "Игроки в поиске клуба", noFreeAgentsFound: "Свободные агенты не найдены.", transferTitle: "Трансферы", walletTitle: "Кошелёк STC", feedTitle: "Лента", post: "Опубликовать", createPost: "Создать пост", share: "Поделиться", delete: "Удалить", newsTitle: "Новости", nothingHere: "Пока пусто", all: "Все", transfers: "Трансферы", contracts: "Контракты", tournaments: "Турниры", recruitmentTitle: "Recruitment", playerPost: "Пост игрока", clubPost: "Пост клуба", playersLooking: "Ищут клуб", clubsRecruiting: "Клубы набирают", trials: "Просмотры", verifiedOnly: "Только верифицированные", postButton: "Опубликовать", showInterest: "Проявить интерес", sendInterest: "Отправить интерес", close: "Закрыть", reopen: "Открыть снова" }),
    ko: base(en, { searchTitle: "검색", searchSubtitle: "선수와 클럽 찾기", searchCta: "검색", playersTab: "선수", myClubsTab: "내 클럽", invite: "초대", challenge: "도전", view: "보기", internationalTitle: "국제", internationalLoading: "국제 토너먼트 로딩 중...", vote: "투표", submitting: "제출 중...", nationalSquad: "대표팀", position: "포지션", saveSquad: "스쿼드 저장", freeAgentTitle: "자유 에이전트", freeAgentSubtitle: "클럽을 찾는 선수", noFreeAgentsFound: "자유 에이전트를 찾을 수 없습니다.", transferTitle: "이적", walletTitle: "STC 지갑", feedTitle: "피드", post: "게시", createPost: "게시물 작성", share: "공유", delete: "삭제", newsTitle: "뉴스", nothingHere: "아직 없음", all: "전체", transfers: "이적", contracts: "계약", tournaments: "토너먼트", recruitmentTitle: "리크루트", playerPost: "선수 게시물", clubPost: "클럽 게시물", playersLooking: "클럽 구함", clubsRecruiting: "클럽 모집", trials: "트라이얼", verifiedOnly: "인증된 사용자만", postButton: "게시", showInterest: "관심 표시", sendInterest: "관심 보내기", close: "닫기", reopen: "다시 열기" }),
    ar: base(en, { searchTitle: "بحث", searchSubtitle: "ابحث عن لاعبين وأندية", searchCta: "بحث", playersTab: "اللاعبون", myClubsTab: "أنديتي", invite: "دعوة", challenge: "تحدّ", view: "عرض", internationalTitle: "دولي", internationalLoading: "جارٍ تحميل البطولات الدولية...", vote: "تصويت", submitting: "جارٍ الإرسال...", nationalSquad: "المنتخب", position: "المركز", saveSquad: "حفظ التشكيلة", freeAgentTitle: "لاعبون أحرار", freeAgentSubtitle: "لاعبون يبحثون عن نادٍ", noFreeAgentsFound: "لم يُعثر على لاعبين أحرار.", transferTitle: "الانتقالات", walletTitle: "محفظة STC", feedTitle: "الخلاصة", post: "نشر", createPost: "إنشاء منشور", share: "مشاركة", delete: "حذف", newsTitle: "الأخبار", nothingHere: "لا شيء هنا بعد", all: "الكل", transfers: "الانتقالات", contracts: "العقود", tournaments: "البطولات", recruitmentTitle: "التوظيف", playerPost: "منشور لاعب", clubPost: "منشور نادي", playersLooking: "يبحثون عن نادٍ", clubsRecruiting: "أندية تستقطب", trials: "تجارب", verifiedOnly: "موثّقون فقط", postButton: "نشر", showInterest: "إبداء اهتمام", sendInterest: "إرسال اهتمام", close: "إغلاق", reopen: "إعادة فتح" }),
    pl: base(en, { searchTitle: "Szukaj", searchSubtitle: "Znajdź graczy i kluby", searchCta: "Szukaj", playersTab: "Gracze", myClubsTab: "Moje kluby", invite: "Zaproś", challenge: "Wyzwij", view: "Zobacz", internationalTitle: "Międzynarodowe", internationalLoading: "Ładowanie turniejów międzynarodowych...", vote: "Głosuj", submitting: "Wysyłanie...", nationalSquad: "Reprezentacja", position: "Pozycja", saveSquad: "Zapisz skład", freeAgentTitle: "Wolni agenci", freeAgentSubtitle: "Gracze szukający klubu", noFreeAgentsFound: "Nie znaleziono wolnych agentów.", transferTitle: "Transfery", walletTitle: "Portfel STC", feedTitle: "Feed", post: "Opublikuj", createPost: "Utwórz post", share: "Udostępnij", delete: "Usuń", newsTitle: "Aktualności", nothingHere: "Jeszcze nic tu nie ma", all: "Wszystko", transfers: "Transfery", contracts: "Kontrakty", tournaments: "Turnieje", recruitmentTitle: "Rekrutacja", playerPost: "Post gracza", clubPost: "Post klubu", playersLooking: "Szukają klubu", clubsRecruiting: "Kluby rekrutują", trials: "Testy", verifiedOnly: "Tylko zweryfikowani", postButton: "Opublikuj", showInterest: "Wyraź zainteresowanie", sendInterest: "Wyślij zainteresowanie", close: "Zamknij", reopen: "Otwórz ponownie" }),
    tr: base(en, { searchTitle: "Ara", searchSubtitle: "Oyuncu ve kulüp bul", searchCta: "Ara", playersTab: "Oyuncular", myClubsTab: "Kulüplerim", invite: "Davet et", challenge: "Meydan oku", view: "Gör", internationalTitle: "Uluslararası", internationalLoading: "Uluslararası turnuvalar yükleniyor...", vote: "Oy ver", submitting: "Gönderiliyor...", nationalSquad: "Milli takım", position: "Pozisyon", saveSquad: "Kadroyu kaydet", freeAgentTitle: "Serbest oyuncular", freeAgentSubtitle: "Kulüp arayan oyuncular", noFreeAgentsFound: "Serbest oyuncu bulunamadı.", transferTitle: "Transferler", walletTitle: "STC Cüzdan", feedTitle: "Akış", post: "Paylaş", createPost: "Gönderi oluştur", share: "Paylaş", delete: "Sil", newsTitle: "Haberler", nothingHere: "Henüz bir şey yok", all: "Tümü", transfers: "Transferler", contracts: "Sözleşmeler", tournaments: "Turnuvalar", recruitmentTitle: "Kadro", playerPost: "Oyuncu gönderisi", clubPost: "Kulüp gönderisi", playersLooking: "Kulüp arıyor", clubsRecruiting: "Kulüpler alım yapıyor", trials: "Denemeler", verifiedOnly: "Yalnızca doğrulanmış", postButton: "Paylaş", showInterest: "İlgi göster", sendInterest: "İlgi gönder", close: "Kapat", reopen: "Yeniden aç" }),
  };
}

export function applyExtendedCommonPageAssigns(commonPageTranslations) {
  for (const [lang, bundle] of Object.entries(homeNotifBundle)) {
    Object.assign(commonPageTranslations[lang], bundle);
  }
}

export function buildExtendedLocalized(matchFlow, competitionFlow, tournamentDetail, commonPages) {
  return {
    ru: { auth: authRu, settingsPage: settingsRu, mobile: mobileRu, nav: navRu, matchFlow: matchFlow.ru, competitionFlow: competitionFlow.ru, tournamentDetail: tournamentDetail.ru, commonPages: commonPages.ru },
    ko: { auth: authKo, settingsPage: settingsKo, mobile: mobileKo, nav: navKo, matchFlow: matchFlow.ko, competitionFlow: competitionFlow.ko, tournamentDetail: tournamentDetail.ko, commonPages: commonPages.ko },
    ar: { auth: authAr, settingsPage: settingsAr, mobile: mobileAr, nav: navAr, matchFlow: matchFlow.ar, competitionFlow: competitionFlow.ar, tournamentDetail: tournamentDetail.ar, commonPages: commonPages.ar },
    pl: { auth: authPl, settingsPage: settingsPl, mobile: mobilePl, nav: navPl, matchFlow: matchFlow.pl, competitionFlow: competitionFlow.pl, tournamentDetail: tournamentDetail.pl, commonPages: commonPages.pl },
    tr: { auth: authTr, settingsPage: settingsTr, mobile: mobileTr, nav: navTr, matchFlow: matchFlow.tr, competitionFlow: competitionFlow.tr, tournamentDetail: tournamentDetail.tr, commonPages: commonPages.tr },
  };
}
