export const COUNTRY_REGIONS = {
  "Europe": ["AT","BE","HR","CZ","DK","FR","DE","GR","IE","IT","NL","NO","PL","PT","RU","RS","ES","SE","CH","TR","UA","GB","AL","AD","AM","AZ","BY","BA","BG","CY","EE","FI","GE","HU","IS","XK","LV","LI","LT","LU","MT","MD","MC","ME","MK","RO","SK","SI","SM","GB-SCT","GB-WLS"],
  "North America": ["CA","MX","US","GT","BZ","HN","SV","NI","CR","PA","CU","JM","HT","DO","TT","BB","LC","VC","GD","AG","DM","KN","BS","PR"],
  "South America": ["AR","BR","CL","CO","PE","VE","EC","BO","PY","UY","GY","SR","GF"],
  "Asia": ["CN","JP","KR","IN","PK","BD","LK","NP","MM","TH","VN","PH","ID","MY","SG","KH","LA","BN","TW","HK","MO","KZ","UZ","TM","KG","TJ","MN","AF","MV","KP","TL","TW"],
  "Oceania": ["AU","NZ","FJ","PG","WS","TO","VU","SB","KI","FM","MH","PW","NR","TV"],
  "Africa": ["CG","CD","EG","MA","NG","ZA","DZ","TN","LY","SD","ET","KE","TZ","UG","RW","BI","DJ","SO","ER","GH","CI","SN","ML","BF","NE","TD","CM","GA","GQ","CF","AO","ZM","ZW","MZ","MW","MG","MU","SC","KM","ST","CV","GM","GW","SL","LR","GN","BJ","TG","SS","LS","SZ","BW","NA","EH"],
  "Middle East": ["SA","AE","QA","KW","BH","OM","IQ","IR","SY","JO","LB","IL","PS","YE"],
};

export const COUNTRIES = [
  // Europe
  { code: "AL", name: "🇦🇱 Albania" },
  { code: "AD", name: "🇦🇩 Andorra" },
  { code: "AM", name: "🇦🇲 Armenia" },
  { code: "AT", name: "🇦🇹 Austria" },
  { code: "AZ", name: "🇦🇿 Azerbaijan" },
  { code: "BE", name: "🇧🇪 Belgium" },
  { code: "BY", name: "🇧🇾 Belarus" },
  { code: "BA", name: "🇧🇦 Bosnia & Herzegovina" },
  { code: "BG", name: "🇧🇬 Bulgaria" },
  { code: "HR", name: "🇭🇷 Croatia" },
  { code: "CY", name: "🇨🇾 Cyprus" },
  { code: "CZ", name: "🇨🇿 Czech Republic" },
  { code: "DK", name: "🇩🇰 Denmark" },
  { code: "EE", name: "🇪🇪 Estonia" },
  { code: "FI", name: "🇫🇮 Finland" },
  { code: "FR", name: "🇫🇷 France" },
  { code: "GE", name: "🇬🇪 Georgia" },
  { code: "DE", name: "🇩🇪 Germany" },
  { code: "GR", name: "🇬🇷 Greece" },
  { code: "HU", name: "🇭🇺 Hungary" },
  { code: "IS", name: "🇮🇸 Iceland" },
  { code: "IE", name: "🇮🇪 Ireland" },
  { code: "IT", name: "🇮🇹 Italy" },
  { code: "XK", name: "🇽🇰 Kosovo" },
  { code: "LV", name: "🇱🇻 Latvia" },
  { code: "LI", name: "🇱🇮 Liechtenstein" },
  { code: "LT", name: "🇱🇹 Lithuania" },
  { code: "LU", name: "🇱🇺 Luxembourg" },
  { code: "MT", name: "🇲🇹 Malta" },
  { code: "MD", name: "🇲🇩 Moldova" },
  { code: "MC", name: "🇲🇨 Monaco" },
  { code: "ME", name: "🇲🇪 Montenegro" },
  { code: "MK", name: "🇲🇰 North Macedonia" },
  { code: "NL", name: "🇳🇱 Netherlands" },
  { code: "NO", name: "🇳🇴 Norway" },
  { code: "PL", name: "🇵🇱 Poland" },
  { code: "PT", name: "🇵🇹 Portugal" },
  { code: "RO", name: "🇷🇴 Romania" },
  { code: "RU", name: "🇷🇺 Russia" },
  { code: "SM", name: "🇸🇲 San Marino" },
  { code: "RS", name: "🇷🇸 Serbia" },
  { code: "SK", name: "🇸🇰 Slovakia" },
  { code: "SI", name: "🇸🇮 Slovenia" },
  { code: "ES", name: "🇪🇸 Spain" },
  { code: "SE", name: "🇸🇪 Sweden" },
  { code: "CH", name: "🇨🇭 Switzerland" },
  { code: "TR", name: "🇹🇷 Turkey" },
  { code: "UA", name: "🇺🇦 Ukraine" },
  { code: "GB", name: "🇬🇧 United Kingdom" },

  // North America
  { code: "AG", name: "🇦🇬 Antigua & Barbuda" },
  { code: "BS", name: "🇧🇸 Bahamas" },
  { code: "BB", name: "🇧🇧 Barbados" },
  { code: "BZ", name: "🇧🇿 Belize" },
  { code: "CA", name: "🇨🇦 Canada" },
  { code: "CR", name: "🇨🇷 Costa Rica" },
  { code: "CU", name: "🇨🇺 Cuba" },
  { code: "DM", name: "🇩🇲 Dominica" },
  { code: "DO", name: "🇩🇴 Dominican Republic" },
  { code: "SV", name: "🇸🇻 El Salvador" },
  { code: "GD", name: "🇬🇩 Grenada" },
  { code: "GT", name: "🇬🇹 Guatemala" },
  { code: "HT", name: "🇭🇹 Haiti" },
  { code: "HN", name: "🇭🇳 Honduras" },
  { code: "JM", name: "🇯🇲 Jamaica" },
  { code: "MX", name: "🇲🇽 Mexico" },
  { code: "NI", name: "🇳🇮 Nicaragua" },
  { code: "PA", name: "🇵🇦 Panama" },
  { code: "PR", name: "🇵🇷 Puerto Rico" },
  { code: "KN", name: "🇰🇳 Saint Kitts & Nevis" },
  { code: "LC", name: "🇱🇨 Saint Lucia" },
  { code: "VC", name: "🇻🇨 Saint Vincent & the Grenadines" },
  { code: "TT", name: "🇹🇹 Trinidad & Tobago" },
  { code: "US", name: "🇺🇸 United States" },

  // South America
  { code: "AR", name: "🇦🇷 Argentina" },
  { code: "BO", name: "🇧🇴 Bolivia" },
  { code: "BR", name: "🇧🇷 Brazil" },
  { code: "CL", name: "🇨🇱 Chile" },
  { code: "CO", name: "🇨🇴 Colombia" },
  { code: "EC", name: "🇪🇨 Ecuador" },
  { code: "GF", name: "🇬🇫 French Guiana" },
  { code: "GY", name: "🇬🇾 Guyana" },
  { code: "PY", name: "🇵🇾 Paraguay" },
  { code: "PE", name: "🇵🇪 Peru" },
  { code: "SR", name: "🇸🇷 Suriname" },
  { code: "UY", name: "🇺🇾 Uruguay" },
  { code: "VE", name: "🇻🇪 Venezuela" },

  // Africa
  { code: "DZ", name: "🇩🇿 Algeria" },
  { code: "AO", name: "🇦🇴 Angola" },
  { code: "BJ", name: "🇧🇯 Benin" },
  { code: "BW", name: "🇧🇼 Botswana" },
  { code: "BF", name: "🇧🇫 Burkina Faso" },
  { code: "BI", name: "🇧🇮 Burundi" },
  { code: "CV", name: "🇨🇻 Cape Verde" },
  { code: "CM", name: "🇨🇲 Cameroon" },
  { code: "CF", name: "🇨🇫 Central African Republic" },
  { code: "TD", name: "🇹🇩 Chad" },
  { code: "KM", name: "🇰🇲 Comoros" },
  { code: "CG", name: "🇨🇬 Congo" },
  { code: "CD", name: "🇨🇩 DR Congo" },
  { code: "CI", name: "🇨🇮 Côte d'Ivoire" },
  { code: "DJ", name: "🇩🇯 Djibouti" },
  { code: "EG", name: "🇪🇬 Egypt" },
  { code: "GQ", name: "🇬🇶 Equatorial Guinea" },
  { code: "ER", name: "🇪🇷 Eritrea" },
  { code: "SZ", name: "🇸🇿 Eswatini" },
  { code: "ET", name: "🇪🇹 Ethiopia" },
  { code: "GA", name: "🇬🇦 Gabon" },
  { code: "GM", name: "🇬🇲 Gambia" },
  { code: "GH", name: "🇬🇭 Ghana" },
  { code: "GN", name: "🇬🇳 Guinea" },
  { code: "GW", name: "🇬🇼 Guinea-Bissau" },
  { code: "KE", name: "🇰🇪 Kenya" },
  { code: "LS", name: "🇱🇸 Lesotho" },
  { code: "LR", name: "🇱🇷 Liberia" },
  { code: "LY", name: "🇱🇾 Libya" },
  { code: "MG", name: "🇲🇬 Madagascar" },
  { code: "MW", name: "🇲🇼 Malawi" },
  { code: "ML", name: "🇲🇱 Mali" },
  { code: "MR", name: "🇲🇷 Mauritania" },
  { code: "MU", name: "🇲🇺 Mauritius" },
  { code: "MA", name: "🇲🇦 Morocco" },
  { code: "MZ", name: "🇲🇿 Mozambique" },
  { code: "NA", name: "🇳🇦 Namibia" },
  { code: "NE", name: "🇳🇪 Niger" },
  { code: "NG", name: "🇳🇬 Nigeria" },
  { code: "RW", name: "🇷🇼 Rwanda" },
  { code: "ST", name: "🇸🇹 São Tomé & Príncipe" },
  { code: "SN", name: "🇸🇳 Senegal" },
  { code: "SC", name: "🇸🇨 Seychelles" },
  { code: "SL", name: "🇸🇱 Sierra Leone" },
  { code: "SO", name: "🇸🇴 Somalia" },
  { code: "ZA", name: "🇿🇦 South Africa" },
  { code: "SS", name: "🇸🇸 South Sudan" },
  { code: "SD", name: "🇸🇩 Sudan" },
  { code: "TZ", name: "🇹🇿 Tanzania" },
  { code: "TG", name: "🇹🇬 Togo" },
  { code: "TN", name: "🇹🇳 Tunisia" },
  { code: "UG", name: "🇺🇬 Uganda" },
  { code: "EH", name: "🇪🇭 Western Sahara" },
  { code: "ZM", name: "🇿🇲 Zambia" },
  { code: "ZW", name: "🇿🇼 Zimbabwe" },

  // Asia
  { code: "AF", name: "🇦🇫 Afghanistan" },
  { code: "BD", name: "🇧🇩 Bangladesh" },
  { code: "BN", name: "🇧🇳 Brunei" },
  { code: "KH", name: "🇰🇭 Cambodia" },
  { code: "CN", name: "🇨🇳 China" },
  { code: "HK", name: "🇭🇰 Hong Kong" },
  { code: "IN", name: "🇮🇳 India" },
  { code: "ID", name: "🇮🇩 Indonesia" },
  { code: "JP", name: "🇯🇵 Japan" },
  { code: "KZ", name: "🇰🇿 Kazakhstan" },
  { code: "KG", name: "🇰🇬 Kyrgyzstan" },
  { code: "LA", name: "🇱🇦 Laos" },
  { code: "MO", name: "🇲🇴 Macao" },
  { code: "MY", name: "🇲🇾 Malaysia" },
  { code: "MV", name: "🇲🇻 Maldives" },
  { code: "MN", name: "🇲🇳 Mongolia" },
  { code: "MM", name: "🇲🇲 Myanmar" },
  { code: "NP", name: "🇳🇵 Nepal" },
  { code: "KP", name: "🇰🇵 North Korea" },
  { code: "PK", name: "🇵🇰 Pakistan" },
  { code: "PH", name: "🇵🇭 Philippines" },
  { code: "SG", name: "🇸🇬 Singapore" },
  { code: "KR", name: "🇰🇷 South Korea" },
  { code: "LK", name: "🇱🇰 Sri Lanka" },
  { code: "TW", name: "🇹🇼 Taiwan" },
  { code: "TJ", name: "🇹🇯 Tajikistan" },
  { code: "TH", name: "🇹🇭 Thailand" },
  { code: "TL", name: "🇹🇱 Timor-Leste" },
  { code: "TM", name: "🇹🇲 Turkmenistan" },
  { code: "UZ", name: "🇺🇿 Uzbekistan" },
  { code: "VN", name: "🇻🇳 Vietnam" },

  // Middle East
  { code: "BH", name: "🇧🇭 Bahrain" },
  { code: "IR", name: "🇮🇷 Iran" },
  { code: "IQ", name: "🇮🇶 Iraq" },
  { code: "IL", name: "🇮🇱 Israel" },
  { code: "JO", name: "🇯🇴 Jordan" },
  { code: "KW", name: "🇰🇼 Kuwait" },
  { code: "LB", name: "🇱🇧 Lebanon" },
  { code: "OM", name: "🇴🇲 Oman" },
  { code: "PS", name: "🇵🇸 Palestine" },
  { code: "QA", name: "🇶🇦 Qatar" },
  { code: "SA", name: "🇸🇦 Saudi Arabia" },
  { code: "SY", name: "🇸🇾 Syria" },
  { code: "AE", name: "🇦🇪 UAE" },
  { code: "YE", name: "🇾🇪 Yemen" },

  // Oceania
  { code: "AU", name: "🇦🇺 Australia" },
  { code: "FJ", name: "🇫🇯 Fiji" },
  { code: "KI", name: "🇰🇮 Kiribati" },
  { code: "MH", name: "🇲🇭 Marshall Islands" },
  { code: "FM", name: "🇫🇲 Micronesia" },
  { code: "NR", name: "🇳🇷 Nauru" },
  { code: "NZ", name: "🇳🇿 New Zealand" },
  { code: "PW", name: "🇵🇼 Palau" },
  { code: "PG", name: "🇵🇬 Papua New Guinea" },
  { code: "WS", name: "🇼🇸 Samoa" },
  { code: "SB", name: "🇸🇧 Solomon Islands" },
  { code: "TO", name: "🇹🇴 Tonga" },
  { code: "TV", name: "🇹🇻 Tuvalu" },
  { code: "VU", name: "🇻🇺 Vanuatu" },
].sort((a, b) => a.name.localeCompare(b.name));