/** English page guides — full paths, not three-line blurbs. */

export const PAGE_GUIDE_STEPS_EN = {
  tournamentMatch: [
    'Open Tournaments, tap your event, then open the fixture that is due.',
    'Read opponent, rules, kickoff window, and the result deadline before you play.',
    'If the time does not work, open match chat or Inbox and propose a new window.',
    'On Game Day, take a dressing-room seat so kickoff can start.',
    'Play the match, then submit the score from this screen — the bracket waits on it.',
    'If the opponent must confirm, stay until their confirm lands or a dispute opens.',
    'Keep a screenshot or clip if the score might be challenged.',
    'After the result sticks, go back to the tournament page for the next round.',
  ],
  tournamentSchedule: [
    'Open Tournaments → your event → Schedule to see every remaining fixture.',
    'Use the round or date filters to find the match that needs you now.',
    'Tap a row to open match detail: opponent, rules, and the action you still owe.',
    'If a window is empty, arrange it from the match or send a time in Inbox.',
    'Check deadlines before you leave — late results stall the whole bracket.',
    'When kickoff is close, jump to Game Day from the fixture card.',
    'After a result, this list updates the next opponent automatically.',
    'Players: confirm you are available. Presidents: make sure the club lineup is set.',
  ],
  tournamentInbox: [
    'Tournament invites, kickoff changes, and admin decisions land here first.',
    'Open an unread item — Accept, Decline, or Reply is usually at the bottom.',
    'An invite is not a registration until you accept it.',
    'A time-change message is not live until both sides accept.',
    'Admin decisions (walkover, dispute, reseeding) also arrive as messages.',
    'After you act, the related fixture on Schedule / Game Day updates.',
    'Do not delete a message that still needs a response — the other side never hears back.',
    'When the inbox is clear, return to the tournament page for the next path.',
  ],
  tournamentPlayers: [
    'Open Tournaments → your event → Players to see who is registered.',
    'Tap a name to open the player profile: position, OVR, club, and record.',
    'Use this before a match to see who is eligible and who is already out.',
    'Presidents: check your own squad is listed before the next deadline.',
    'If someone is missing, they may still need to accept an invite in Inbox.',
    'Open a profile, then Inbox or Transfer Market if you need to recruit mid-event.',
    'Compare form on Rankings if two players look similar on paper.',
    'Return to the fixture when you know who you are facing.',
  ],
  tournamentClubs: [
    'Open Tournaments → your event → Clubs to see every participating team.',
    'Tap a club to open its page: squad, president, record, and trophies.',
    'Use this before match day to learn the opponent’s spine and who is on loan.',
    'Presidents: confirm your club is registered here, not only on your own profile.',
    'If your club is missing, go to Register or the tournament entry button.',
    'From a club page you can open the president, the squad, or THE STAGE TIMES coverage.',
    'Do not recruit from a tournament-limited club unless the event allows it.',
    'When you know the opponent, go to Schedule or Game Day for that fixture.',
  ],
  matches: [
    'Game Day is the pitch: play, confirm, stream, and finish the result.',
    'Start from Home or the Matches tab, or jump here from a Schedule row.',
    'Open the match card for opponent, competition, kickoff, chat, and stream.',
    'Set Availability on your player profile so the president can pick a window.',
    'Take a dressing-room seat. Kickoff stays blocked until both sides seat someone.',
    'After the game, submit the score. The away side usually has to confirm.',
    'If the score is wrong, open a dispute and attach evidence — do not only chat.',
    'Unread match chat is cleared when you open Game Day. Check it before you leave.',
    'Next fixture lives on Schedule. Cups and leagues live under Competitions / Tournaments.',
  ],
  compete: [
    'Competitions is the menu of leagues and cups your club can enter.',
    'Open a competition for format, entry rules, table, and the register action.',
    'The club enters — not your personal player profile.',
    'If a season is open, continue to Register and submit before the deadline.',
    'After entry, fixtures appear on Schedule and then on Game Day.',
    'Standings, matchdays, and champions sit on the competition page itself.',
    'One-off cups and brackets also live under Tournaments.',
    'National teams and country events live under International.',
    'THE STAGE TIMES → Competitions / Tournaments reports what just happened.',
  ],
  club: [
    'Your club page is the public shop window: crest, squad, record, and office.',
    'Open it from Profile (Club tab) or a news / ranking link.',
    'Squad: tap a player for profile, contract, release, role, or loan actions.',
    'Feed: club posts. Operations: applicants, staff, lineups (if you can run ops).',
    'Office is president-only: Contracts, Stadium, Finance, Shirts, Trophies, History, Chat.',
    'Players do not join with a public Join button — they sign a contract from Inbox.',
    'To leave as a player, use Leave Club on your profile. That ends the live deal.',
    'Find other clubs from Search, Rankings, or THE STAGE TIMES club files.',
    'Recruit from Transfer Market, Free Agents, or Scouting — then Inbox to finish.',
  ],
  schedule: [
    'Schedule is the calendar. Game Day is where you actually play.',
    'Open Schedule from Apps or from a competition / tournament page.',
    'Use the calendar or list to find the fixture that still needs a time or a result.',
    'Tap a row to open detail, then Arrange / propose a time if the window is empty.',
    'Time proposals also appear in Inbox — accept them there if you missed the card.',
    'When the window is confirmed, the same fixture appears on Game Day.',
    'Contract reminders (expiry) can sit on this calendar too — open them before they lapse.',
    'After full time, return here to see the next matchday.',
  ],
  inbox: [
    'Inbox is the decision desk: contracts, loans, match times, club messages.',
    'Open Apps → Inbox, or tap a notification. Unread usually means you owe an action.',
    'Contract offer: read wage, length, and type, then Accept, Counter, or Decline.',
    'Loan proposal: parent club, then the player, must accept before it goes live.',
    'Loan return / buy-out messages use the same card — Accept or Reject there.',
    'Match invite or time change: Accept, Decline, or propose a new date.',
    'Do not delete a message that still needs a response.',
    'After you accept a contract you leave Free Agents and appear on that club’s squad.',
    'After you accept a loan you play for the borrowing club until recall, return, or buy.',
    'Clear Inbox, then go to Schedule / Game Day or Club Office for the next job.',
  ],
  tournaments: [
    'Tournaments lists cups and events. Open one for rules, clubs, players, and schedule.',
    'Presidents register the club from the event page or from Register.',
    'Players check that they are on the registered squad before the first deadline.',
    'Use the event’s Schedule for fixtures, Inbox for invites, Game Day to play.',
    'Clubs and Players tabs on the event are the directories for that bracket.',
    'Admins and eligible presidents manage the event from the tournament controls.',
    'Results you submit on Game Day move this bracket. Late scores freeze it.',
    'THE STAGE TIMES → Tournaments covers champions, phases, and field news.',
  ],
  international: [
    'International is for national competitions and country-based events.',
    'Open a card for eligibility, squad rules, and the current phase.',
    'Country is usually taken from your club or player country code.',
    'Follow the page actions in order: register, vote, build squad, then play.',
    'Votes and squad picks are club-president actions unless the page says otherwise.',
    'Fixtures from this desk still land on Schedule and Game Day.',
    'If you are not eligible, the page will say why — do not force a Register elsewhere.',
    'News from these events also appears on THE STAGE TIMES World / Competitions desks.',
  ],
  register: [
    'Register is only for an open league or season window.',
    'Read requirements: club vs player entry, region, roster size, deadline.',
    'Choose the club (or player) the form asks for, then submit once.',
    'A pending registration is not a fixture yet — wait for confirmation.',
    'After you are in, open that competition for the table and matchdays.',
    'Fixtures then appear on Schedule. Play them on Game Day.',
    'Inbox may send an entry confirmation or a missing-document request.',
    'If the window is closed, watch THE STAGE TIMES or Competitions for the next one.',
  ],
  rankings: [
    'Rankings compare players and clubs by form, not by transfer rumour.',
    'Switch player vs club, then tap a row to open the full profile.',
    'Presidents: use this as a first scout list, then open Free Agents or Transfer Market.',
    'Players: this is how other clubs see your rating and record.',
    'A ranking row is not a contract. Offers still go through Inbox.',
    'Country and region chips help you find local rivals.',
    'From a profile you can follow, offer a contract, or request a loan.',
    'Match results on Game Day are what move these numbers.',
  ],
  players: [
    'Find Players is the public player directory.',
    'Search by name, then open a profile for position, OVR, club, and showcase.',
    'Presidents: this is a scout start. Next stop is Scouting, then a contract offer.',
    'Players: compare yourself and find teammates or rivals.',
    'A signed player already has a club — use Request Loan, not a contract offer.',
    'A free agent has no club — send a contract from their profile or Club Office.',
    'Follow someone from the profile if you want their feed later.',
    'Inbox is where the offer actually gets accepted.',
  ],
  presidents: [
    'Presidents is a directory of club leaders, separate from the player list.',
    'Open a row for the president profile and the club they run.',
    'Use this when you want to talk to the person who signs contracts, not a squad player.',
    'From their club page you can see squad, office tools, and competition place.',
    'Arrange a match or send a message from the paths the profile offers.',
    'Do not confuse a president profile with a player contract — they are different seats.',
    'Player + President accounts switch with the identity rail on Profile.',
    'News about clubs often names the president on THE STAGE TIMES Club desk.',
  ],
  freeAgents: [
    'Free Agents are players with no live club contract.',
    'Open Apps → Free Agents, or wait until THE STAGE TIMES Mercato flags a free deal.',
    'Tap a player, read wage history, position, and showcase clips.',
    'Presidents: send a contract offer from the profile or Club Office → Contracts.',
    'Choose type (trial, academy, squad, important, star). Founder Player is not for recruits.',
    'The player answers in Inbox. Until they accept, they stay on this list.',
    'Do not use Request Loan here — loans need a parent club.',
    'After they sign, they leave this list and appear on your Squad tab.',
  ],
  scouting: [
    'Scouting is the club shortlist, not a public join board.',
    'File a report on a player with notes and video links.',
    'The president can open a squad vote. The vote is advisory only.',
    'The president decides: send a contract from the report, or shelve it.',
    'Open the player from the report to see the live profile and market status.',
    'If they are signed elsewhere, switch to a loan request instead of a contract.',
    'Accepted deals leave Scouting and show on Squad / Contracts.',
    'Keep reports honest — presidents and players will open the same clips.',
  ],
  transfers: [
    'Transfer Market is where signed players and listed deals live.',
    'Filter by position, value, or availability, then open the player.',
    'On a signed player, a president of another club taps Request Loan — not Join.',
    'Loan terms: dates, fee, wage split, recall, and option or obligation to buy.',
    'The parent club accepts in Inbox, then the player accepts, then the loan activates.',
    'Permanent moves still go through a contract offer, not a silent transfer.',
    'Mercato stories on THE STAGE TIMES open the same player and club files.',
    'Your own listed players are managed from Club Office and the squad gamecards.',
  ],
  wallet: [
    'Wallet is your personal STC, not the club finance pot.',
    'Collect weekly salary only while a player contract is active.',
    'Match and cup prizes land here after Game Day results confirm.',
    'Open a transaction before you spend — Lifestyle and Store take from this balance.',
    'STAGE Plus and credits are separate from club STC.',
    'Presidents: club wages and prizes are under Club → Office → Finance.',
    'If a payment looks wrong, keep the row visible before you contact an admin.',
    'Leave Club stops the wage. A live loan may split that wage with the parent club.',
  ],
  feed: [
    'Feed is the social layer: posts, follows, and club moments.',
    'Open it from Apps or Social. Post from your player or club surface.',
    'Tap a name to open the profile, a crest to open the club, a story to open News.',
    'Follow Back (Apps) shows who follows you so you can return the follow.',
    'Match results and contracts do not complete here — those stay in Inbox / Game Day.',
    'Use Discord for voice and community chat; use Inbox for private deals.',
    'Keep the feed useful: lineups and wins help recruitment more than empty posts.',
    'From a post you can always jump to Profile, Club, or THE STAGE TIMES.',
  ],
  discord: [
    'Discord is the community room, not the place contracts are signed.',
    'Open Apps → Discord for the invite and server widget.',
    'Use it for voice lobbies, announcements, and wider talk.',
    'Match times, contract offers, and loan replies still belong in Inbox.',
    'Game Day chat is for that fixture only — do not rely on Discord for official times.',
    'Admins may post rule changes here and in THE STAGE TIMES. Read both.',
    'If a link is missing, check Settings or the community page again later.',
    'Come back to Schedule / Game Day when a fixture is actually due.',
  ],
  followBack: [
    'Follow Back lists people who follow you but you do not follow yet.',
    'Open a row to read the player or president profile first.',
    'Follow from the profile if you want their feed and match noise.',
    'This does not sign a contract or add them to your squad.',
    'Presidents still recruit from Free Agents, Transfer Market, or Scouting.',
    'Unfollow from their profile if the follow was a mistake.',
    'Your own followers also appear on your public profile activity.',
    'Return to Feed to see the posts after you follow.',
  ],
  profile: [
    'Profile is your public player card: OVR, club, record, showcase, availability.',
    'Edit from the pencil: position, platform, country, bio, and avatar.',
    'Showcase clips are what presidents watch before they send an offer.',
    'Availability tells your club when you can play Game Day.',
    'If you are a free agent, clubs find you on Free Agents and Transfer Market.',
    'If you are signed, another club can Request Loan from this page.',
    'Leave Club ends the live contract and puts you back on the market.',
    'Player + President accounts switch Player / President / Club on this hub.',
    'Trophies, lifestyle, and EA FC link sit under More on the player surface.',
  ],
  search: [
    'Search is the fastest jump to a player, club, or president you can name.',
    'Type a gamertag, club name, or tag, then open the result.',
    'Player result → profile (contract, loan, follow).',
    'Club result → club page (squad, office, competitions).',
    'Use Find Players when you are browsing, not searching a name.',
    'Rankings and THE STAGE TIMES are better when you do not know the name yet.',
    'A search hit is not an offer. Finish deals in Inbox.',
    'From any result you can always go back and search the opponent next.',
  ],
  lifestyle: [
    'Lifestyle is optional flavour: assets, clothes, and identity items priced in STC.',
    'Open Wallet first so you know the personal balance.',
    'Tap an item for price, effect, rent vs buy, and upkeep.',
    'Purchases do not replace a contract wage and do not sign you to a club.',
    'Some assets can add a small passive income — read the card before you buy.',
    'Club STC (Finance) cannot be spent here. This is personal wallet only.',
    'After a buy, the item appears on your profile / lifestyle tab.',
    'Store is for STAGE Plus and unlocks. Lifestyle is for in-world assets.',
  ],
  store: [
    'Store is for STAGE Plus, unlocks, and paid extras — not club wages.',
    'Open an item for cost, what it unlocks, and how long it lasts.',
    'Wallet (personal) and any credit balance are what you pay with.',
    'Club Finance is a different pot. Do not expect a shirt sale to pay a Store item.',
    'After purchase, Settings and your profile show the active perk.',
    'Cancellations and renewals are explained on the item and in Wallet history.',
    'Lifestyle sits next door if you meant an in-world asset instead.',
    'If a charge looks wrong, keep the Wallet row and contact an admin.',
  ],
  news: [
    'THE STAGE TIMES is the newspaper: All, Mercato, Club, Player, Tournaments, Competitions, Daily, World.',
    'All is the mixed front page. Tap a story for the full file and club / player links.',
    'Mercato is transfers, contracts, and market tape — not the same as Transfer Market deals.',
    'Club News: stadium, shirts, tickets, trophies. Player News: lifestyle, rankings, MOTM.',
    'Tournaments and Competitions desks follow brackets, tables, and champions.',
    'Daily News is today only. World News: pick a continent, then a country chip.',
    'UK stories may use GB, UK, ENG, SCO, WAL, or NIR — they count as the same desk.',
    'A story is a file, not an action. Sign, loan, and play still go through Inbox and Game Day.',
    'Use Club file / player links on a story to jump straight into the app path.',
  ],
  dashboard: [
    'Home is the command center: next match, inbox pressure, and shortcuts into Apps.',
    'A fixture tile jumps to Game Day. A calendar tile jumps to Schedule.',
    'Unread Inbox means a contract, loan, or time proposal is waiting.',
    'Club tiles open your club page (squad, office, finance).',
    'Apps (the grid) is how you reach Transfer Market, Free Agents, News, Wallet, Register.',
    'Profile tab is your player / president / club identity rail.',
    'Tournaments tab is cups. Competitions live under Apps if you need the league table.',
    'If you feel lost, open Settings → How STAGE works, or tap Guide on the page you are on.',
  ],
  contracts: [
    'Contracts lists offers you sent or received: pending, active, declined, talks.',
    'Open a row to see wage, length, type, and the player or club on the other side.',
    'Players accept, counter, or decline in Inbox — this list is the ledger.',
    'Presidents send new offers from Club Office or from a player profile.',
    'Types: trial, academy, squad, important, star. Founder Player is only for club creation.',
    'A live contract is what puts a player on the squad. Terminating it is Release.',
    'Loans do not replace the parent contract. They add a playing-rights deal on top.',
    'When a deal is waiting on someone, Inbox is the place they will see it.',
  ],
};
